### ISSUE TITLE
Markdown preview not the same as what's displayed in post

### ISSUE THREAD

**Issue by gabeguz** [GetGoBlog/GoBlog#25]
Two things I've noticed so far, in the editor, when you use the 

`#` and `##` notation to indicate headings, things look fine, but when you view the post live, the `#` and `##`'s don't get properly rendered to headings, instead they just appear inline.  See:  http://cotcli.goblog.pw/welcome-to-comfort-on-the-command-line/  for an example.   The first `##` heading (Welcome to Comfort on the Command Line) has no space after it, the next one (What is the Command Line Interface (cli)) _does_ have a space.  Strangely either way works fine in the editor but only the one with a space after works properly on the blog itself. 

The second thing is that using "``" to start a code section renders differently in the live preview than it does on the published post.  In the live preview if you do: 

```
  `` 
  some code here
  ``
```

Everything will look fine, but on the blog post, you'll see an extra whitespace at the top of your code section.  Using three backticks does work as expected, however.  

Otherwise, things are going great... I like it so far, and I hope you all keep working on this!

**Comment by farazfazli** [comment]
Thanks! Are you putting a space in between your hash # and your heading? Make sure you're doing it like this:

```
# Heading here
```

Also, headings need an empty line after them to appear properly. For code, surround it with three back ticks ```

I'm glad you enjoy GoBlog, I am constantly working on trying to improve the user experience. :)

**Comment by gabeguz** [comment]
Yeah, I figure out that it needed a space, but the "live preview" renders it correctly without the space... I'm guessing it's two different markdown libraries?   One javascript one for the live preview and a go one for the final blog post?

**Comment by gabeguz** [comment]
Also. the two backticks comes from the markdown "help" guide in the preview, so maybe that's just some documentation that needs to be updated to show 3 instead of 2.

**Comment by farazfazli** [comment]
Yup, I'm thinking about changing it to use the Go blackfriday library completely.

Thanks for the info, I will change the help guide.
